### ISSUE TITLE
能否根据某个具体的PPT文件计时？

### ISSUE THREAD

**Issue by swaggerz** [old9/ppttimer#3]
有时演讲人会因为各种原因退出全屏模式，但演讲并未中断，一退一进，ppttimer重新计时，不太符合实际情况，我的想法是根据某个具体的PPT文件，全屏后开始计时，只要它不退出，一直计时，不知可否？

**Comment by old9** [comment]
“退出”的定义比较难确定。
你说的这种场景，我感觉手动计时比较好。可以设置一个 flag，手动计时的时候不检测 PPT 状态。

**Comment by swaggerz** [comment]
手动计时也可以，很期待更新，谢谢

**Comment by old9** [comment]
已增加手动计时不自动检测计时的参数设置
