### ISSUE TITLE
能否增加对WPS Office的支持？

### ISSUE THREAD

**Issue by karegyudon** [old9/ppttimer#5]
您好，感谢提供一个非常有用的工具软件，不过测试下来似乎不支持WPS Office的演示部件，不知能否添加相关支持。

WPS Office演示窗口window classname是QWidget

**Comment by old9** [comment]
应该可以通过标题判断

> WPS演示 幻灯片放映 - [演示文稿1]
> ahk_class QWidget

**Comment by old9** [comment]
修改了检测逻辑为检测全屏程序，这样可以支持更多演示程序
