### ISSUE TITLE
能否支持输出到第二显示器

### ISSUE THREAD

**Issue by duduhappy2003** [old9/ppttimer#6]
由于需要在述职会等会议上投屏到大屏幕使用，如果能支持显示到第二显示器就好，电脑就可以用拓展模式了，免得把桌面投屏到大屏避免意外社死（bushi
：）

**Comment by chenisshuaibi** [comment]
+1

**Comment by old9** [comment]
已支持在多显示器间轮转，默认快捷键 Ctrl+Win+M

**Comment by chenisshuaibi** [comment]
感谢 @old9
